
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "3003:3003"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/usr/src/app/dist  
    depends_on:
      - backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  frontend_build:
